In [24]:
import numpy as np
import random
from time import sleep

# Create an empty board
def create_board():
    return np.array([[0, 0, 0],
                     [0, 0, 0],
                     [0, 0, 0]])

# Check for empty places on the board
def possibilities(board):
    l = []
    for i in range(len(board)):
        for j in range(len(board[i])):
            if board[i][j] == 0:
                l.append((i, j))
    return l

# Select a random place for the player
def random_place(board, player):
    selection = possibilities(board)
    if selection:  # Check if there are available moves
        current_loc = random.choice(selection)
        board[current_loc] = player
    return board

# Check whether the player has a horizontal win
def row_win(board, player):
    for x in range(len(board)):
        if all([spot == player for spot in board[x, :]]):
            return True
    return False

# Check whether the player has a vertical win
def col_win(board, player):
    for x in range(len(board)):
        if all([spot == player for spot in board[:, x]]):
            return True
    return False

# Check whether the player has a diagonal win
def diag_win(board, player):
    if all([board[i, i] == player for i in range(len(board))]):
        return True
    if all([board[i, len(board) - i - 1] == player for i in range(len(board))]):
        return True
    return False

# Evaluate whether there is a winner or a tie
def evaluate(board):
    winner = 0
    for player in [1, 2]:
        if row_win(board, player) or col_win(board, player) or diag_win(board, player):
            winner = player
    if np.all(board != 0) and winner == 0:
        winner = -1  # -1 indicates a tie
    return winner

# Main function to start the game
def play_game():
    board, winner, counter = create_board(), 0, 1
    print("Initial board:")
    print(board)
    sleep(2)

    while winner == 0:
        for player in [1, 2]:
            board = random_place(board, player)
            print(f"Board after {counter} move(s):")
            print(board)
            sleep(2)
            counter += 1
            winner = evaluate(board)
            if winner != 0:
                break
    return winner

# Driver code
print("Winner is: " + str(play_game()))



Initial board:
[[0 0 0]
 [0 0 0]
 [0 0 0]]
Board after 1 move(s):
[[0 1 0]
 [0 0 0]
 [0 0 0]]
Board after 2 move(s):
[[0 1 0]
 [0 0 0]
 [0 0 2]]
Board after 3 move(s):
[[0 1 0]
 [0 0 0]
 [0 1 2]]
Board after 4 move(s):
[[0 1 0]
 [0 2 0]
 [0 1 2]]
Board after 5 move(s):
[[0 1 1]
 [0 2 0]
 [0 1 2]]
Board after 6 move(s):
[[0 1 1]
 [0 2 2]
 [0 1 2]]
Board after 7 move(s):
[[0 1 1]
 [0 2 2]
 [1 1 2]]
Board after 8 move(s):
[[0 1 1]
 [2 2 2]
 [1 1 2]]
Winner is: 2
